version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      BITNAMI_DEBUG : "false"
      ZOO_DATA_LOG_DIR : ""
      ZOO_PORT_NUMBER : "2181"
      ZOO_TICK_TIME : "2000"
      ZOO_INIT_LIMIT : "10"
      ZOO_SYNC_LIMIT : "5"
      ZOO_PRE_ALLOC_SIZE : "65536"
      ZOO_SNAPCOUNT : "100000"
      ZOO_MAX_CLIENT_CNXNS : "60"
      ZOO_4LW_COMMANDS_WHITELIST : "srvr, mntr, ruok"
      ZOO_LISTEN_ALLIPS_ENABLED : "no"
      ZOO_AUTOPURGE_INTERVAL : "0"
      ZOO_AUTOPURGE_RETAIN_COUNT : "3"
      ZOO_MAX_SESSION_TIMEOUT : "40000"
      ZOO_ENABLE_AUTH : "no"
      ZOO_ENABLE_QUORUM_AUTH : "no"
      ZOO_HEAP_SIZE : "1024"
      ZOO_LOG_LEVEL : "ERROR"
      ALLOW_ANONYMOUS_LOGIN : "yes"

  broker:
    image: bitnami/kafka:latest
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BOOTSTRAP.SERVERS: 'broker:9093'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS : PLAINTEXT://:9093,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9093,PLAINTEXT_HOST://localhost:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      ALLOW_PLAINTEXT_LISTENER : "yes"

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9093'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021